In [2]:
import numpy as np
import pandas as pd

In [14]:
perfil_afinidad = pd.read_csv('../csvs/perfil_afinidad_celulas_29, Obtener perfiles de afinidad.csv')
perfil_afinidad['id_compuestos_actividad'] = perfil_afinidad['id_compuestos_actividad'].str.replace("[","")
perfil_afinidad['id_compuestos_actividad'] = perfil_afinidad['id_compuestos_actividad'].str.replace("]","")
perfil_afinidad

C:\Users\Reyum\AppData\Local\Temp\ipykernel_8144\2518517562.py:2: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  perfil_afinidad['id_compuestos_actividad'] = perfil_afinidad['id_compuestos_actividad'].str.replace("[","")
C:\Users\Reyum\AppData\Local\Temp\ipykernel_8144\2518517562.py:3: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  perfil_afinidad['id_compuestos_actividad'] = perfil_afinidad['id_compuestos_actividad'].str.replace("]","")

      cell_id                            id_compuestos_actividad
0           1                 2580, 5105, 13590, 178357, 1148287
1           2                             42503, 444713, 1337017
2           3  5769, 16758, 16949, 103459, 287231, 446279, 23...
3           5  717, 2208, 5105, 5268, 8633, 11305, 13590, 499...
4           7                            68607, 1704201, 1704202
...       ...                                                ...
1464     5924                   232036, 232036, 2469807, 2469807
1465     5927                                             462435
1466     5928                                      25906, 183934
1467     5930                                             368538
1468     5931  923, 2471419, 2471677, 2471958, 2473036, 24753...

[1469 rows x 2 columns]

In [100]:
top3 = pd.read_csv('../csvs/top3_with_smiles, fix_top3.csv')
top3['top3'] = top3['top3'].str.replace("[","")
top3['top3'] = top3['top3'].str.replace("]","")
top3

C:\Users\Reyum\AppData\Local\Temp\ipykernel_8144\944545554.py:2: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  top3['top3'] = top3['top3'].str.replace("[","")
C:\Users\Reyum\AppData\Local\Temp\ipykernel_8144\944545554.py:3: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  top3['top3'] = top3['top3'].str.replace("]","")

,comp_id,top3,id_29,pref_name,smiles
0,30,"11852, 1025, 41",789,METOPROLOL,COCCc1ccc(OCC(O)CNC(C)C)cc1
1,35,,1022,ARECOLINE,COC(=O)C1=CCCN(C)C1
2,37,"732, 1969, 12063",1216,TRIMETHOPRIM,COc1cc(Cc2cnc(N)nc2N)cc(OC)c1OC
3,43,"253, 9820, 195",1370,PROPRANOLOL,CC(C)NCC(O)COc1cccc2ccccc12
4,74,"423, 16216, 16217",2214,SEROTONIN,NCCc1c[nH]c2ccc(O)cc12
...,...,...,...,...,...
133,38360,"38361, 2954, 2982",1745509,NaN,NCCCNCCCNC1CCCCCCCCCCCCCC1
134,38886,,1786544,NaN,CS(=O)(=O)N[C@@H](c1ccc(CNC[C@H]2COc3cccnc3O2)...
135,39403,"3001, 3002, 3000",141871,NaN,CCc1cc2c3[nH]c4c(N)cccc4c3cc[n+]2nc1CC
136,46946,"46954, 46962, 15475",2055476,NaN,CC1CCCN(CCCCCOc2ccc(Cl)cc2)C1
137,46961,"46948, 46953, 46956",2055491,NaN,Clc1ccc(OCCCCCCCN2CCCCC2)cc1

In [110]:
[top3['top3']]

[0          11852, 1025, 41
 1
 2         732, 1969, 12063
 3           253, 9820, 195
 4        423, 16216, 16217
               ...
 133      38361, 2954, 2982
 134
 135       3001, 3002, 3000
 136    46954, 46962, 15475
 137    46948, 46953, 46956
 Name: top3, Length: 138, dtype: object]

In [111]:
for i in range(top3['comp_id'].size):
#     print(top3.iloc[i]['comp_id'])
    op = top3.iloc[i][top3.columns[1].split(', ')]
    op = op[0].split(', ')
    for i in op:
        var = top3[top3['comp_id'] == i]
        print(var)

# op = top3.iloc[4][top3.columns[1].split(', ')]
# op = op[0].split(', ')
# print(op)
# for i in op:
#     var = top3[top3['comp_id'] == 35]
#     print(var)

Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]

Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []
Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []

In [67]:
perfil_afinidad.iloc[2][perfil_afinidad.columns[1]]
for i in range(perfil_afinidad['cell_id'].size):
    print (perfil_afinidad.iloc[i])
# perfil_afinidad[perfil_afinidad.columns[2]]
# perfil_afinidad[perfil_afinidad.columns[2]]

cell_id                                                     1
id_compuestos_actividad    2580, 5105, 13590, 178357, 1148287
Name: 0, dtype: object
cell_id                                         2
id_compuestos_actividad    42503, 444713, 1337017
Name: 1, dtype: object
cell_id                                                                    3
id_compuestos_actividad    5769, 16758, 16949, 103459, 287231, 446279, 23...
Name: 2, dtype: object
cell_id                                                                    5
id_compuestos_actividad    717, 2208, 5105, 5268, 8633, 11305, 13590, 499...
Name: 3, dtype: object
cell_id                                          7
id_compuestos_actividad    68607, 1704201, 1704202
Name: 4, dtype: object
cell_id                         9
id_compuestos_actividad    399526
Name: 5, dtype: object
cell_id                       10
id_compuestos_actividad    29831
Name: 6, dtype: object
cell_id                        11
id_compuestos_actividad    322288
Name: 7, dtype: object
cell_id                                                                   13
id_compuestos_actividad    717, 2208, 5105, 5268, 8633, 11305, 13590, 499...
Name: 8, dtype: object
cell_id                       16
id_compuestos_actividad    29831
Name: 9, dtype: object
cell_id                              19
id_compuestos_actividad    16547, 16634
Name: 10, dtype: object
cell_id                                                                   21
id_compuestos_actividad    717, 2208, 5105, 5268, 8633, 11305, 13590, 362...
Name: 11, dtype: object
cell_id                                                      26
id_compuestos_actividad    13633, 68607, 190171, 236838, 365281
Name: 12, dtype: object
cell_id                                                                   27
id_compuestos_actividad    22942, 22943, 78759, 160849, 161022, 1143686, ...
Name: 13, dtype: object
cell_id                                28
id_compuestos_actividad    136087, 136438
Name: 14, dtype: object
cell_id                                29
id_compuestos_actividad    160849, 161022
Name: 15, dtype: object
cell_id                                                                31
id_compuestos_actividad    107431, 107508, 108296, 108327, 108902, 108946
Name: 16, dtype: object
cell_id                        32
id_compuestos_actividad    368538
Name: 17, dtype: object
cell_id                                    35
id_compuestos_actividad    8633, 16592, 68607
Name: 18, dtype: object
cell_id                                                                   37
id_compuestos_actividad    717, 923, 2080, 5268, 8062, 8633, 11501, 13048...
Name: 19, dtype: object
cell_id                                                                   38
id_compuestos_actividad    717, 923, 2080, 2208, 5105, 5268, 8062, 8633, ...
Name: 20, dtype: object
cell_id                                                                   39
id_compuestos_actividad    717, 2208, 5105, 5268, 5295, 5985, 8633, 11305...
Name: 21, dtype: object
cell_id                                                                   42
id_compuestos_actividad    8633, 29325, 29325, 49931, 51182, 78759, 14286...
Name: 22, dtype: object
cell_id                                                                   43
id_compuestos_actividad    27307, 76862, 82983, 94364, 154407, 233915, 23...
Name: 23, dtype: object
cell_id                       44
id_compuestos_actividad    63279
Name: 24, dtype: object
cell_id                                                                   45
id_compuestos_actividad    3859, 8633, 14440, 16592, 49931, 68607, 75901,...
Name: 25, dtype: object
cell_id                                               46
id_compuestos_actividad    51182, 78759, 457363, 1376110
Name: 26, dtype: object
cell_id                      48
id_compuestos_actividad    5371
Name: 27, dtype: object
cell_id                               50
id_compuestos_actividad    27307, 166091
Name: 28, dtype: object
cell_id                                                                   53
id_compuestos_actividad    13590, 14529, 78759, 128914, 246935, 470511, 5...
Name: 29, dtype: object
cell_id                                           54
id_compuestos_actividad    1214046, 1763587, 2470081
Name: 30, dtype: object
cell_id                                      55
id_compuestos_actividad    87293, 87712, 226708
Name: 31, dtype: object
cell_id                       56
id_compuestos_actividad    51182
Name: 32, dtype: object
cell_id                      57
id_compuestos_actividad    1219
Name: 33, dtype: object
cell_id                                                                   58
id_compuestos_actividad    717, 2208, 5105, 5268, 5295, 8062, 8633, 11305...
Name: 34, dtype: object
cell_id                        60
id_compuestos_actividad    374019
Name: 35, dtype: object
cell_id                                   61
id_compuestos_actividad    2580, 4504, 68607
Name: 36, dtype: object
cell_id                                       63
id_compuestos_actividad    25906, 373381, 373381
Name: 37, dtype: object
cell_id                                                     64
id_compuestos_actividad    2658, 39672, 118583, 198067, 198357
Name: 38, dtype: object
cell_id                                                                   66
id_compuestos_actividad    717, 2208, 5105, 5268, 6579, 8633, 11305, 1359...
Name: 39, dtype: object
cell_id                                         69
id_compuestos_actividad    68607, 1704201, 1704202
Name: 40, dtype: object
cell_id                                70
id_compuestos_actividad    160849, 161022
Name: 41, dtype: object
cell_id                                                                   73
id_compuestos_actividad    717, 2208, 5105, 5268, 8062, 8633, 11305, 1359...
Name: 42, dtype: object
cell_id                                        74
id_compuestos_actividad    202260, 202595, 203042
Name: 43, dtype: object
cell_id                                                                   75
id_compuestos_actividad    717, 2208, 5105, 5268, 5295, 8633, 11305, 1359...
Name: 44, dtype: object
cell_id                         76
id_compuestos_actividad    2021521
Name: 45, dtype: object
cell_id                                                           77
id_compuestos_actividad    19101, 35874, 49931, 63535, 64671, 374019
Name: 46, dtype: object
cell_id                                                                   81
id_compuestos_actividad    4843, 4843, 5043, 5049, 5049, 5089, 5095, 5098...
Name: 47, dtype: object
cell_id                               90
id_compuestos_actividad    6968, 1408997
Name: 48, dtype: object
cell_id                                                                   95
id_compuestos_actividad    717, 923, 2080, 5268, 8062, 13048, 13590, 1478...
Name: 49, dtype: object
cell_id                                96
id_compuestos_actividad    160849, 161022
Name: 50, dtype: object
cell_id                                                                   97
id_compuestos_actividad    717, 923, 2208, 5105, 5105, 5268, 5295, 8062, ...
Name: 51, dtype: object
cell_id                                                                   98
id_compuestos_actividad    78759, 88797, 426660, 430664, 2343831, 2355259...
Name: 52, dtype: object
cell_id                                       101
id_compuestos_actividad    78759, 522730, 1331852
Name: 53, dtype: object
cell_id                      103
id_compuestos_actividad    18696
Name: 54, dtype: object
cell_id                             104
id_compuestos_actividad    16547, 16634
Name: 55, dtype: object
cell_id                           105
id_compuestos_actividad    8062, 8633
Name: 56, dtype: object
cell_id                                                                  106
id_compuestos_actividad    4496, 5295, 8062, 14440, 50068, 50077, 50078, ...
Name: 57, dtype: object
cell_id                                                                  110
id_compuestos_actividad    8633, 13590, 78759, 222232, 245881, 245881, 46...
Name: 58, dtype: object
cell_id                     112
id_compuestos_actividad    5105
Name: 59, dtype: object
cell_id                     116
id_compuestos_actividad    8633
Name: 60, dtype: object
cell_id                                                               117
id_compuestos_actividad    107431, 107508, 108296, 108327, 108902, 108946
Name: 61, dtype: object
cell_id                               118
id_compuestos_actividad    160849, 161022
Name: 62, dtype: object
cell_id                                120
id_compuestos_actividad    624225, 1581943
Name: 63, dtype: object
cell_id                                                                  122
id_compuestos_actividad    717, 923, 2080, 2208, 5105, 5268, 8062, 8633, ...
Name: 64, dtype: object
cell_id                               123
id_compuestos_actividad    160849, 161022
Name: 65, dtype: object
cell_id                       124
id_compuestos_actividad    103459
Name: 66, dtype: object
cell_id                                                                  125
id_compuestos_actividad    27307, 193952, 377611, 1076153, 1155085, 13369...
Name: 67, dtype: object
cell_id                               128
id_compuestos_actividad    160849, 161022
Name: 68, dtype: object
cell_id                             132
id_compuestos_actividad    2580, 180615
Name: 69, dtype: object
cell_id                                                                  133
id_compuestos_actividad    5105, 336913, 1512632, 1512633, 1512634, 15793...
Name: 70, dtype: object
cell_id                                                                  137
id_compuestos_actividad    717, 923, 2080, 5268, 8062, 8633, 13048, 13590...
Name: 71, dtype: object
cell_id                                                    140
id_compuestos_actividad    29325, 29325, 31146, 116927, 117236
Name: 72, dtype: object
cell_id                                                                  141
id_compuestos_actividad    5105, 5295, 5295, 6402, 6579, 8062, 8062, 1130...
Name: 73, dtype: object
cell_id                                                                  142
id_compuestos_actividad    2658, 5105, 6968, 172779, 304798, 1283609, 128...
Name: 74, dtype: object
cell_id                       151
id_compuestos_actividad    232640
Name: 75, dtype: object
cell_id                       152
id_compuestos_actividad    232640
Name: 76, dtype: object
cell_id                     153
id_compuestos_actividad    6914
Name: 77, dtype: object
cell_id                                                                  154
id_compuestos_actividad    717, 2208, 4775, 4775, 5105, 5268, 7427, 8633,...
Name: 78, dtype: object
cell_id                               156
id_compuestos_actividad    417248, 465506
Name: 79, dtype: object
cell_id                                                                  158
id_compuestos_actividad    717, 2208, 5105, 5268, 8633, 11305, 13590, 145...
Name: 80, dtype: object
cell_id                               159
id_compuestos_actividad    160849, 161022
Name: 81, dtype: object
cell_id                                                   160
id_compuestos_actividad    22942, 49931, 90393, 90396, 365281
Name: 82, dtype: object
cell_id                                                                  163
id_compuestos_actividad    8062, 27307, 47675, 49931, 51182, 78759, 82982...
Name: 83, dtype: object
cell_id                                                                  164
id_compuestos_actividad    5295, 5295, 6104, 8062, 14440, 54712, 88797, 1...
Name: 84, dtype: object
cell_id                                                                  165
id_compuestos_actividad    717, 2208, 5105, 5268, 8633, 11305, 13590, 499...
Name: 85, dtype: object
cell_id                          166
id_compuestos_actividad    860, 2658
Name: 86, dtype: object
cell_id                                                                  169
id_compuestos_actividad    4584, 9128, 19316, 261089, 513723, 579828, 579...
Name: 87, dtype: object
cell_id                                     170
id_compuestos_actividad    5295, 78759, 2200045
Name: 88, dtype: object
cell_id                                                                  171
id_compuestos_actividad    58818, 160170, 160650, 193952, 341064, 365284,...
Name: 89, dtype: object
cell_id                       172
id_compuestos_actividad    419596
Name: 90, dtype: object
cell_id                                                                  173
id_compuestos_actividad    717, 2208, 5105, 5268, 8633, 11305, 13590, 147...
Name: 91, dtype: object
cell_id                      175
id_compuestos_actividad    51182
Name: 92, dtype: object
cell_id                      176
id_compuestos_actividad    88797
Name: 93, dtype: object
cell_id                                             178
id_compuestos_actividad    27307, 27307, 281080, 281080
Name: 94, dtype: object
cell_id                                             180
id_compuestos_actividad    5295, 75901, 161178, 2387448
Name: 95, dtype: object
cell_id                       181
id_compuestos_actividad    390877
Name: 96, dtype: object
cell_id                                                                  185
id_compuestos_actividad    2580, 13590, 18841, 19706, 29831, 32553, 51896...
Name: 97, dtype: object
cell_id                       186
id_compuestos_actividad    368538
Name: 98, dtype: object
cell_id                                                                  187
id_compuestos_actividad    8062, 14440, 71516, 1163586, 1163588, 1163594,...
Name: 99, dtype: object
cell_id                                                                  188
id_compuestos_actividad    8062, 14440, 71516, 1163586, 1163588, 1163594,...
Name: 100, dtype: object
cell_id                                     189
id_compuestos_actividad    44165, 44488, 175594
Name: 101, dtype: object
cell_id                                                                 190
id_compuestos_actividad    441561, 441563, 602271, 651088, 2357504, 2357504
Name: 102, dtype: object
cell_id                                             191
id_compuestos_actividad    16758, 16949, 103459, 287231
Name: 103, dtype: object
cell_id                                                                  193
id_compuestos_actividad    8062, 28853, 71516, 560078, 1440750, 1440751, ...
Name: 104, dtype: object
cell_id                                                                  194
id_compuestos_actividad    11305, 138562, 382029, 382033, 382035, 417180,...
Name: 105, dtype: object
cell_id                      195
id_compuestos_actividad    78759
Name: 106, dtype: object
cell_id                                                                  196
id_compuestos_actividad    5295, 21789, 21791, 49931, 54135, 54662, 37401...
Name: 107, dtype: object
cell_id                                                                  198
id_compuestos_actividad    717, 923, 2080, 5268, 8062, 13048, 13590, 1478...
Name: 108, dtype: object
cell_id                                                                  201
id_compuestos_actividad    173, 2658, 8873, 103658, 239549, 319603, 36528...
Name: 109, dtype: object
cell_id                                                                  204
id_compuestos_actividad    35108, 35874, 35982, 36294, 36533, 36769, 3679...
Name: 110, dtype: object
cell_id                                                                  207
id_compuestos_actividad    207003, 207190, 207211, 207226, 207405, 207426...
Name: 111, dtype: object
cell_id                     208
id_compuestos_actividad    8633
Name: 112, dtype: object
cell_id                      213
id_compuestos_actividad    27307
Name: 113, dtype: object
cell_id                                                                  217
id_compuestos_actividad    923, 2080, 5105, 7501, 8062, 13048, 14785, 148...
Name: 114, dtype: object
cell_id                      219
id_compuestos_actividad    51182
Name: 115, dtype: object
cell_id                                                                  220
id_compuestos_actividad    717, 3859, 5268, 8633, 13590, 16592, 22942, 49...
Name: 116, dtype: object
cell_id                                    221
id_compuestos_actividad    63252, 82763, 82763
Name: 117, dtype: object
cell_id                                                               222
id_compuestos_actividad    107431, 107508, 108296, 108327, 108902, 108946
Name: 118, dtype: object
cell_id                                                    223
id_compuestos_actividad    8062, 78759, 187596, 187649, 188011
Name: 119, dtype: object
cell_id                                      225
id_compuestos_actividad    13449, 364693, 453189
Name: 120, dtype: object
cell_id                                                       226
id_compuestos_actividad    11305, 11305, 590141, 1844293, 1844293
Name: 121, dtype: object
cell_id                               227
id_compuestos_actividad    160849, 161022
Name: 122, dtype: object
cell_id                                                                  228
id_compuestos_actividad    717, 2208, 5105, 5268, 8633, 11305, 13590, 499...
Name: 123, dtype: object
cell_id                                   229
id_compuestos_actividad    717, 51929, 114733
Name: 124, dtype: object
cell_id                                                                  231
id_compuestos_actividad    717, 923, 2208, 5105, 5268, 8062, 8633, 11305,...
Name: 125, dtype: object
cell_id                                                                  233
id_compuestos_actividad    717, 2208, 5105, 5268, 8633, 11305, 13590, 147...
Name: 126, dtype: object
cell_id                                                                  237
id_compuestos_actividad    717, 923, 2080, 2208, 5105, 5268, 8062, 8633, ...
Name: 127, dtype: object
cell_id                            238
id_compuestos_actividad    5295, 46106
Name: 128, dtype: object
cell_id                                                                  241
id_compuestos_actividad    173, 717, 2208, 5105, 5268, 8633, 11305, 13590...
Name: 129, dtype: object
cell_id                                            242
id_compuestos_actividad    9097, 14805, 319858, 470511
Name: 130, dtype: object
cell_id                       244
id_compuestos_actividad    626299
Name: 131, dtype: object
cell_id                                                                  246
id_compuestos_actividad    717, 2208, 5105, 5105, 5268, 8062, 8633, 11305...
Name: 132, dtype: object
cell_id                                                                  248
id_compuestos_actividad    5105, 7501, 8667, 12437, 78759, 214533, 214602...
Name: 133, dtype: object
cell_id                                                               249
id_compuestos_actividad    146324, 146469, 146828, 147109, 147291, 147292
Name: 134, dtype: object
cell_id                      251
id_compuestos_actividad    51182
Name: 135, dtype: object
cell_id                                                                  252
id_compuestos_actividad    717, 923, 2080, 2208, 5105, 5268, 8062, 8633, ...
Name: 136, dtype: object
cell_id                                                                  255
id_compuestos_actividad    717, 923, 2080, 2208, 5105, 5268, 8062, 8633, ...
Name: 137, dtype: object
cell_id                        256
id_compuestos_actividad    2083644
Name: 138, dtype: object
cell_id                                                                  257
id_compuestos_actividad    11305, 11501, 382029, 382033, 382035, 382037, ...
Name: 139, dtype: object
cell_id                                                                  258
id_compuestos_actividad    2208, 5105, 8633, 11305, 47579, 49931, 51182, ...
Name: 140, dtype: object
cell_id                                                                  259

Name: 456, dtype: object
cell_id                                                                  651
id_compuestos_actividad    717, 2208, 2580, 4504, 4775, 5105, 5105, 5268,...
Name: 457, dtype: object
cell_id                                                                  652
id_compuestos_actividad    675, 675, 892, 5105, 5105, 5295, 5575, 5575, 8...
Name: 458, dtype: object
cell_id                                                                  653
id_compuestos_actividad    717, 923, 2080, 2208, 2223, 2223, 5105, 5268, ...
Name: 459, dtype: object
cell_id                                                                  654
id_compuestos_actividad    717, 923, 2080, 5268, 8062, 13048, 13590, 1478...
Name: 460, dtype: object
cell_id                                                                  655
id_compuestos_actividad    148, 173, 717, 799, 860, 923, 1219, 1413, 1763...
Name: 461, dtype: object
cell_id                                                                  656
id_compuestos_actividad    1219, 1219, 5105, 5105, 5295, 5389, 5985, 7501...
Name: 462, dtype: object
cell_id                                                                  657
id_compuestos_actividad    148, 717, 1413, 1763, 2080, 2093, 2208, 2580, ...
Name: 463, dtype: object
cell_id                                                                  659
id_compuestos_actividad    2067, 27307, 27307, 224386, 296388, 356894, 35...
Name: 464, dtype: object
cell_id                                                                  660
id_compuestos_actividad    173, 717, 923, 2080, 2208, 2812, 4775, 5105, 5...
Name: 465, dtype: object
cell_id                                                                  661
id_compuestos_actividad    11305, 11305, 42503, 46106, 47675, 75901, 7590...
Name: 466, dtype: object
cell_id                                                                  662
id_compuestos_actividad    29948, 29948, 80669, 204711, 205737, 263633, 2...
Name: 467, dtype: object
cell_id                                                                  663
id_compuestos_actividad    892, 924, 4370, 10661, 12957, 16437, 41530, 65...
Name: 468, dtype: object
cell_id                                                          664
id_compuestos_actividad    611336, 611338, 1444086, 1444093, 1444768
Name: 469, dtype: object
cell_id                                                                  665
id_compuestos_actividad    7501, 276734, 367509, 444829, 464347, 1277745,...
Name: 470, dtype: object
cell_id                                                                  666
id_compuestos_actividad    1763, 29325, 49931, 78759, 368538, 575613, 236...
Name: 471, dtype: object
cell_id                                                                  667
id_compuestos_actividad    148, 717, 923, 2080, 2208, 2580, 2812, 3012, 4...
Name: 472, dtype: object
cell_id                                                                  668
id_compuestos_actividad    148, 717, 799, 923, 1413, 1763, 2080, 2093, 22...
Name: 473, dtype: object
cell_id                                                                  669
id_compuestos_actividad    799, 1413, 1763, 2080, 2093, 2208, 2580, 2658,...
Name: 474, dtype: object
cell_id                                                                  671
id_compuestos_actividad    924, 2658, 4504, 4504, 5105, 7501, 8062, 8633,...
Name: 475, dtype: object
cell_id                                                                  672
id_compuestos_actividad    491, 2658, 4504, 5295, 5622, 6402, 6914, 6914,...
Name: 476, dtype: object
cell_id                                                                  673
id_compuestos_actividad    1763, 1994, 2214, 4149, 6005, 8062, 8633, 1222...
Name: 477, dtype: object
cell_id                                                               674
id_compuestos_actividad    403324, 520116, 520118, 520202, 520353, 520420
Name: 478, dtype: object
cell_id                                                                  675
id_compuestos_actividad    717, 2208, 5105, 5268, 8633, 11305, 13590, 499...
Name: 479, dtype: object
cell_id                                                                  676
id_compuestos_actividad    148, 717, 799, 1413, 1763, 2080, 2093, 2208, 2...
Name: 480, dtype: object
cell_id                                                                  677
id_compuestos_actividad    14366, 14785, 14805, 276734, 365284, 575319, 5...
Name: 481, dtype: object
cell_id                             680
id_compuestos_actividad    8062, 276734
Name: 482, dtype: object
cell_id                       681
id_compuestos_actividad    467361
Name: 483, dtype: object
cell_id                                                             684
id_compuestos_actividad    3965, 419596, 453570, 485021, 698208, 698208
Name: 484, dtype: object
cell_id                       685
id_compuestos_actividad    490427
Name: 485, dtype: object
cell_id                      686
id_compuestos_actividad    78759
Name: 486, dtype: object
cell_id                                                                  687
id_compuestos_actividad    717, 799, 1219, 1219, 1413, 1763, 2080, 2093, ...
Name: 487, dtype: object
cell_id                                                       688
id_compuestos_actividad    72873, 365281, 376676, 460144, 1448219
Name: 488, dtype: object
cell_id                                                                  690
id_compuestos_actividad    148, 717, 799, 923, 1413, 1763, 2080, 2093, 22...
Name: 489, dtype: object
cell_id                                                                  691
id_compuestos_actividad    424, 424, 465, 465, 534, 534, 603, 603, 2580, ...
Name: 490, dtype: object
cell_id                                                                  692
id_compuestos_actividad    1219, 2812, 5970, 47675, 75577, 78759, 82983, ...
Name: 491, dtype: object
cell_id                                                                  693
id_compuestos_actividad    717, 2208, 2658, 4504, 4504, 5105, 5105, 5268,...
Name: 492, dtype: object
cell_id                                                                  694
id_compuestos_actividad    173, 717, 1763, 2208, 4775, 5105, 5105, 5268, ...
Name: 493, dtype: object
cell_id                                                                  696
id_compuestos_actividad    4775, 5575, 5769, 11305, 11501, 14440, 36237, ...
Name: 494, dtype: object
cell_id                                                                  697
id_compuestos_actividad    1763, 4775, 5105, 5295, 5797, 8062, 8682, 8682...
Name: 495, dtype: object
cell_id                                                                  698
id_compuestos_actividad    717, 2208, 5105, 5268, 8633, 11305, 13590, 157...
Name: 496, dtype: object
cell_id                                                                  700
id_compuestos_actividad    49931, 62806, 62818, 78759, 82297, 111132, 129...
Name: 497, dtype: object
cell_id                                                                  701
id_compuestos_actividad    148, 717, 799, 923, 1413, 1763, 2080, 2093, 22...
Name: 498, dtype: object
cell_id                                                                  702
id_compuestos_actividad    173, 250, 2749, 3784, 3784, 19517, 37812, 1356...
Name: 499, dtype: object
cell_id                                                                  703
id_compuestos_actividad    1763, 6104, 71232, 71378, 373381, 387585, 2279071
Name: 500, dtype: object
cell_id                                                                  704
id_compuestos_actividad    717, 2208, 5105, 5105, 5268, 5295, 7427, 8633,...
Name: 501, dtype: object
cell_id                      705
id_compuestos_actividad    60597
Name: 502, dtype: object
cell_id                                                                  706
id_compuestos_actividad    2658, 14440, 14440, 75901, 364693, 368538, 226...
Name: 503, dtype: object
cell_id                                 707
id_compuestos_actividad    2472622, 2476589
Name: 504, dtype: object
cell_id                                                                  708
id_compuestos_actividad    173, 1763, 2658, 13633, 30884, 71232, 103658, ...
Name: 505, dtype: object
cell_id                      709
id_compuestos_actividad    78759
Name: 506, dtype: object
cell_id                                                               710
id_compuestos_actividad    14440, 78759, 142808, 190171, 1143686, 1334185
Name: 507, dtype: object
cell_id                      711
id_compuestos_actividad    49931
Name: 508, dtype: object
cell_id                                                    712
id_compuestos_actividad    5295, 69890, 161178, 361088, 361102
Name: 509, dtype: object
cell_id                       713
id_compuestos_actividad    121457
Name: 510, dtype: object
cell_id                                                                  714
id_compuestos_actividad    717, 2208, 5105, 5268, 8633, 11305, 13590, 499...
Name: 511, dtype: object
cell_id                                                                  715
id_compuestos_actividad    148, 717, 799, 923, 1413, 1763, 2080, 2093, 22...
Name: 512, dtype: object
cell_id                       716
id_compuestos_actividad    510946
Name: 513, dtype: object
cell_id                                                                  717
id_compuestos_actividad    717, 923, 1219, 2080, 2208, 3784, 5105, 5105, ...
Name: 514, dtype: object
cell_id                                                                  718
id_compuestos_actividad    818, 818, 857, 857, 858, 858, 1763, 1892, 1892...
Name: 515, dtype: object
cell_id                                                                  719
id_compuestos_actividad    5105, 5295, 8062, 8633, 15738, 49931, 68607, 7...
Name: 516, dtype: object
cell_id                              720
id_compuestos_actividad    44488, 175594
Name: 517, dtype: object
cell_id                                                                  721
id_compuestos_actividad    148, 173, 213, 717, 799, 1219, 1219, 1413, 176...
Name: 518, dtype: object
cell_id                                                                  722
id_compuestos_actividad    97, 97, 148, 173, 250, 415, 415, 436, 436, 573...
Name: 519, dtype: object
cell_id                                                                  723
id_compuestos_actividad    860, 892, 1219, 1756, 1756, 1763, 2208, 2208, ...
Name: 520, dtype: object
cell_id                        725
id_compuestos_actividad    1178704
Name: 521, dtype: object
cell_id                                                                  726
id_compuestos_actividad    173, 860, 923, 924, 1219, 1763, 2080, 2080, 22...
Name: 522, dtype: object
cell_id                                                                  727
id_compuestos_actividad    142808, 368538, 382168, 382175, 402387, 402412...
Name: 523, dtype: object
cell_id                                                                  730
id_compuestos_actividad    148, 717, 799, 923, 1413, 1756, 1763, 2080, 20...
Name: 524, dtype: object
cell_id                                                     732
id_compuestos_actividad    18694, 38843, 438579, 438579, 438618
Name: 525, dtype: object
cell_id                                                                  735
id_compuestos_actividad    3854, 3965, 6968, 7501, 21938, 68607, 154798, ...
Name: 526, dtype: object
cell_id                     737
id_compuestos_actividad    8062
Name: 527, dtype: object
cell_id                                                                  738
id_compuestos_actividad    191999, 318474, 338339, 338339, 509467, 509467...
Name: 528, dtype: object
cell_id                                                                  740
id_compuestos_actividad    717, 923, 2080, 2208, 4775, 5105, 5268, 5295, ...
Name: 529, dtype: object
cell_id                                                                  741
id_compuestos_actividad    148, 717, 799, 923, 1413, 1763, 2080, 2093, 22...
Name: 530, dtype: object
cell_id                                                             742
id_compuestos_actividad    8062, 183934, 381244, 381247, 381251, 393442
Name: 531, dtype: object
cell_id                                                                  743
id_compuestos_actividad    148, 717, 799, 923, 1413, 1763, 2080, 2093, 22...
Name: 532, dtype: object
cell_id                                                                  744
id_compuestos_actividad    148, 2208, 2580, 2812, 5295, 5575, 6972, 7343,...
Name: 533, dtype: object
cell_id                                                                  746
id_compuestos_actividad    717, 2208, 5105, 5268, 5295, 7501, 8062, 8633,...
Name: 534, dtype: object
cell_id                                                                  747
id_compuestos_actividad    148, 717, 799, 1413, 1763, 2080, 2093, 2208, 2...
Name: 535, dtype: object
cell_id                                                                  748
id_compuestos_actividad    3784, 4504, 4775, 5295, 5575, 6088, 6104, 7427...
Name: 536, dtype: object
cell_id                                                                  749
id_compuestos_actividad    148, 675, 1763, 2658, 2812, 3012, 3998, 4496, ...
Name: 537, dtype: object
cell_id                                                                  750
id_compuestos_actividad    3998, 5105, 8062, 8633, 11305, 14440, 14785, 1...
Name: 538, dtype: object
cell_id                                                                  751
id_compuestos_actividad    1763, 5105, 8062, 78759, 103658, 172779, 19017...
Name: 539, dtype: object
cell_id                                                                  752
id_compuestos_actividad    717, 923, 2080, 2208, 5105, 5268, 8062, 8633, ...
Name: 540, dtype: object
cell_id                                                                  753
id_compuestos_actividad    148, 717, 799, 923, 1413, 1763, 2080, 2093, 22...
Name: 541, dtype: object
cell_id                                                                  754
id_compuestos_actividad    148, 717, 799, 1370, 1413, 1763, 1785, 2080, 2...
Name: 542, dtype: object
cell_id                                                                  755
id_compuestos_actividad    148, 799, 1370, 1413, 1763, 1785, 2080, 2093, ...
Name: 543, dtype: object
cell_id                                                                  756
id_compuestos_actividad    892, 4775, 5575, 7501, 8062, 36237, 68607, 787...
Name: 544, dtype: object
cell_id                                                                  757
id_compuestos_actividad    148, 717, 923, 1413, 1763, 2080, 2093, 2208, 2...
Name: 545, dtype: object
cell_id                                                                  758
id_compuestos_actividad    3998, 5105, 22942, 25906, 51182, 68607, 78759,...
Name: 546, dtype: object
cell_id                                                                  761
id_compuestos_actividad    717, 2208, 5105, 5268, 8062, 8633, 11305, 1304...
Name: 547, dtype: object
cell_id                                                                  763
id_compuestos_actividad    148, 717, 799, 923, 1413, 1763, 2080, 2093, 22...
Name: 548, dtype: object
cell_id                                                                  764
id_compuestos_actividad    4504, 5295, 51182, 78759, 417248, 2013100, 232...
Name: 549, dtype: object
cell_id                       765
id_compuestos_actividad    430664
Name: 550, dtype: object
cell_id                                                                  767
id_compuestos_actividad    202110, 202260, 202427, 202442, 202443, 202595...
Name: 551, dtype: object
cell_id                                                              768
id_compuestos_actividad    5105, 8633, 9097, 14440, 68607, 78759, 373381
Name: 552, dtype: object
cell_id                                                                  770
id_compuestos_actividad    148, 173, 717, 799, 924, 1413, 1756, 1763, 208...
Name: 553, dtype: object
cell_id                                                                  771
id_compuestos_actividad    148, 2214, 2214, 3859, 4345, 5105, 5295, 5295,...
Name: 554, dtype: object
cell_id                                                                  773
id_compuestos_actividad    1763, 2580, 3847, 3848, 5105, 5295, 5295, 5575...
Name: 555, dtype: object
cell_id                      774
id_compuestos_actividad    27307
Name: 556, dtype: object
cell_id                                                                  776
id_compuestos_actividad    717, 923, 2080, 2208, 5105, 5268, 8062, 8633, ...
Name: 557, dtype: object
cell_id                                                                  778
id_compuestos_actividad    5105, 15738, 68607, 162058, 190171, 360948, 37...
Name: 558, dtype: object
cell_id                                                                  779
id_compuestos_actividad    1763, 5105, 5295, 6968, 8062, 11305, 12588, 12...
Name: 559, dtype: object
cell_id                                           780
id_compuestos_actividad    5575, 6216, 104385, 108846
Name: 560, dtype: object
cell_id                                              781
id_compuestos_actividad    49931, 208640, 258448, 258450
Name: 561, dtype: object
cell_id                                                                  782
id_compuestos_actividad    1219, 4504, 5105, 5284, 5284, 5295, 5389, 5985...
Name: 562, dtype: object
cell_id                                             783
id_compuestos_actividad    11305, 11501, 326884, 332325
Name: 563, dtype: object
cell_id                                                                  784
id_compuestos_actividad    717, 2208, 2658, 5105, 5105, 5268, 8633, 11305...
Name: 564, dtype: object
cell_id                             785
id_compuestos_actividad    5295, 348794
Name: 565, dtype: object
cell_id                                                                  786
id_compuestos_actividad    148, 173, 717, 799, 1413, 1763, 2080, 2093, 22...
Name: 566, dtype: object
cell_id                                                                  787
id_compuestos_actividad    148, 717, 799, 923, 1413, 1763, 2080, 2093, 22...
Name: 567, dtype: object
cell_id                       788
id_compuestos_actividad    220887
Name: 568, dtype: object
cell_id                                                                  789
id_compuestos_actividad    799, 1413, 1763, 2080, 2093, 2208, 2580, 2658,...
Name: 569, dtype: object
cell_id                                                                  790
id_compuestos_actividad    2580, 5295, 6968, 7501, 8062, 14440, 71516, 10...
Name: 570, dtype: object
cell_id                                                                  791
id_compuestos_actividad    173, 1763, 4504, 4775, 4775, 5105, 5105, 5268,...
Name: 571, dtype: object
cell_id                                                                  792
id_compuestos_actividad    5295, 8062, 68607, 78759, 332293, 332298, 3323...
Name: 572, dtype: object
cell_id                                       793
id_compuestos_actividad    78759, 480382, 1591769
Name: 573, dtype: object
cell_id                      794
id_compuestos_actividad    14366
Name: 574, dtype: object
cell_id                                                                  796
id_compuestos_actividad    717, 923, 1756, 2080, 5105, 5268, 8062, 8633, ...
Name: 575, dtype: object
cell_id                                                                  797
id_compuestos_actividad    717, 2208, 3859, 5105, 5105, 5268, 6104, 7501,...
Name: 576, dtype: object
cell_id                                                                  798
id_compuestos_actividad    1763, 2214, 4775, 5295, 5575, 8062, 8062, 8633...
Name: 577, dtype: object
cell_id                                                                  799

Name: 921, dtype: object
cell_id                                                                 1398
id_compuestos_actividad    717, 2208, 5105, 5268, 8633, 11305, 13590, 499...
Name: 922, dtype: object
cell_id                                                                 1399
id_compuestos_actividad    717, 2208, 5105, 5105, 5268, 8633, 11305, 1359...
Name: 923, dtype: object
cell_id                                                                 1400
id_compuestos_actividad    717, 2208, 5105, 5268, 5575, 8633, 11305, 1359...
Name: 924, dtype: object
cell_id                                                                 1401
id_compuestos_actividad    717, 923, 2080, 2208, 5105, 5268, 8062, 8633, ...
Name: 925, dtype: object
cell_id                                                                 1402
id_compuestos_actividad    717, 923, 2080, 2208, 2580, 5105, 5268, 6968, ...
Name: 926, dtype: object
cell_id                                                                 1403
id_compuestos_actividad    717, 2208, 5105, 8633, 11305, 13590, 49931, 51...
Name: 927, dtype: object
cell_id                                                                 1404
id_compuestos_actividad    2208, 5105, 8633, 11305, 49931, 51182, 62111, ...
Name: 928, dtype: object
cell_id                                                                 1405
id_compuestos_actividad    717, 2208, 5105, 5268, 8633, 11305, 13590, 499...
Name: 929, dtype: object
cell_id                                                                 1406
id_compuestos_actividad    717, 2208, 5105, 5268, 8633, 11305, 13590, 499...
Name: 930, dtype: object
cell_id                                                                 1407
id_compuestos_actividad    717, 2208, 5105, 5268, 8633, 11305, 13590, 499...
Name: 931, dtype: object
cell_id                                                                 1408
id_compuestos_actividad    717, 2208, 5105, 5268, 8633, 11305, 13590, 499...
Name: 932, dtype: object
cell_id                                                                 1409
id_compuestos_actividad    717, 5268, 8062, 13590, 56713, 68607, 75901, 7...
Name: 933, dtype: object
cell_id                                                                 1410
id_compuestos_actividad    717, 2208, 5105, 5268, 8633, 11305, 13590, 499...
Name: 934, dtype: object
cell_id                                                                 1411
id_compuestos_actividad    717, 2208, 5105, 5268, 8633, 11305, 13590, 499...
Name: 935, dtype: object
cell_id                                                                 1412
id_compuestos_actividad    717, 2208, 5105, 5268, 8633, 11305, 13590, 499...
Name: 936, dtype: object
cell_id                                                                 1413
id_compuestos_actividad    717, 2208, 5105, 5268, 8633, 11305, 13590, 499...
Name: 937, dtype: object
cell_id                                                                 1415
id_compuestos_actividad    717, 2208, 5105, 5268, 8633, 11305, 13590, 499...
Name: 938, dtype: object
cell_id                                                                 1416
id_compuestos_actividad    717, 2208, 5105, 5268, 8062, 8633, 11305, 1359...
Name: 939, dtype: object
cell_id                                                                 1417
id_compuestos_actividad    717, 2208, 5105, 5268, 8633, 11305, 13590, 499...
Name: 940, dtype: object
cell_id                                                                 1418
id_compuestos_actividad    717, 2208, 5105, 5268, 8062, 8633, 11305, 1359...
Name: 941, dtype: object
cell_id                                                                 1419
id_compuestos_actividad    717, 1763, 2208, 5105, 5268, 8633, 11305, 1359...
Name: 942, dtype: object
cell_id                                                                 1422
id_compuestos_actividad    717, 2208, 5105, 5268, 8633, 11305, 13590, 499...
Name: 943, dtype: object
cell_id                                                                 1424
id_compuestos_actividad    717, 2208, 5105, 5268, 8633, 11305, 13590, 499...
Name: 944, dtype: object
cell_id                                                                 1425
id_compuestos_actividad    717, 2208, 5105, 5268, 8062, 8633, 11305, 1359...
Name: 945, dtype: object
cell_id                                                                 1426
id_compuestos_actividad    717, 2208, 5105, 5268, 8633, 11305, 13590, 499...
Name: 946, dtype: object
cell_id                                                                 1427
id_compuestos_actividad    2208, 5105, 8633, 11305, 49931, 51182, 62111, ...
Name: 947, dtype: object
cell_id                                                                 1429
id_compuestos_actividad    717, 2208, 5105, 5268, 8062, 8633, 11305, 1359...
Name: 948, dtype: object
cell_id                                                                 1430
id_compuestos_actividad    717, 2208, 5105, 5268, 8633, 11305, 11501, 135...
Name: 949, dtype: object
cell_id                                                                 1431
id_compuestos_actividad    717, 5268, 13590, 56713, 68607, 75901, 78759, ...
Name: 950, dtype: object
cell_id                                                                 1432
id_compuestos_actividad    717, 923, 2080, 2208, 5105, 5268, 8062, 8633, ...
Name: 951, dtype: object
cell_id                                                                 1433
id_compuestos_actividad    2208, 5105, 8633, 11305, 49931, 51182, 62111, ...
Name: 952, dtype: object
cell_id                                                                 1434
id_compuestos_actividad    717, 923, 2080, 2208, 5105, 5268, 8062, 8633, ...
Name: 953, dtype: object
cell_id                                                                 1435
id_compuestos_actividad    717, 923, 2080, 2208, 5105, 5268, 8062, 8633, ...
Name: 954, dtype: object
cell_id                                                                 1436
id_compuestos_actividad    717, 923, 2080, 2208, 5105, 5268, 8062, 8633, ...
Name: 955, dtype: object
cell_id                                                                 1437
id_compuestos_actividad    717, 923, 2080, 2208, 5105, 5268, 8062, 8633, ...
Name: 956, dtype: object
cell_id                                                                 1438
id_compuestos_actividad    717, 923, 2080, 5268, 8062, 8062, 13048, 13590...
Name: 957, dtype: object
cell_id                                                                 1439
id_compuestos_actividad    717, 5268, 13048, 13590, 56713, 68607, 75901, ...
Name: 958, dtype: object
cell_id                                                                 1440
id_compuestos_actividad    717, 923, 2080, 5268, 8062, 13048, 13590, 1478...
Name: 959, dtype: object
cell_id                                                                 1441
id_compuestos_actividad    717, 923, 2080, 2208, 2812, 5105, 5268, 8062, ...
Name: 960, dtype: object
cell_id                                                                 1442
id_compuestos_actividad    717, 923, 2080, 2208, 5105, 5268, 8062, 8633, ...
Name: 961, dtype: object
cell_id                                                                 1443
id_compuestos_actividad    717, 923, 2080, 5268, 8062, 11305, 13048, 1359...
Name: 962, dtype: object
cell_id                                                                 1444
id_compuestos_actividad    717, 923, 2080, 2208, 5105, 5268, 8062, 8633, ...
Name: 963, dtype: object
cell_id                                                                 1445
id_compuestos_actividad    717, 923, 2080, 5268, 8062, 13048, 13590, 1478...
Name: 964, dtype: object
cell_id                                                                 1446
id_compuestos_actividad    717, 923, 2080, 2208, 5105, 5268, 8062, 8633, ...
Name: 965, dtype: object
cell_id                                                                 1447
id_compuestos_actividad    717, 923, 2080, 2208, 5105, 5268, 8062, 8633, ...
Name: 966, dtype: object
cell_id                                                                 1448
id_compuestos_actividad    717, 923, 2080, 2208, 5105, 5268, 8062, 8633, ...
Name: 967, dtype: object
cell_id                                                                 1449
id_compuestos_actividad    717, 923, 2080, 2208, 5105, 5268, 8062, 8633, ...
Name: 968, dtype: object
cell_id                                                                 1450
id_compuestos_actividad    717, 923, 2080, 2208, 5105, 5268, 8062, 8633, ...
Name: 969, dtype: object
cell_id                                                                 1451
id_compuestos_actividad    717, 923, 2080, 2208, 5105, 5268, 8062, 8633, ...
Name: 970, dtype: object
cell_id                                                                 1452
id_compuestos_actividad    717, 923, 2080, 2208, 5105, 5268, 8062, 8633, ...
Name: 971, dtype: object
cell_id                                                                 1453
id_compuestos_actividad    717, 923, 2080, 2208, 5105, 5268, 8062, 8633, ...
Name: 972, dtype: object
cell_id                                                                 1454
id_compuestos_actividad    717, 923, 2080, 2208, 5105, 5268, 8062, 8633, ...
Name: 973, dtype: object
cell_id                                                                 1455
id_compuestos_actividad    717, 923, 2208, 5105, 5268, 8062, 8633, 11305,...
Name: 974, dtype: object
cell_id                                                                 1456
id_compuestos_actividad    717, 923, 2080, 5268, 8062, 11305, 13048, 1359...
Name: 975, dtype: object
cell_id                                                                 1457
id_compuestos_actividad    717, 923, 2080, 2208, 5105, 5268, 8062, 8633, ...
Name: 976, dtype: object
cell_id                                                                 1458
id_compuestos_actividad    717, 923, 2080, 2208, 5105, 5268, 8062, 8633, ...
Name: 977, dtype: object
cell_id                                                                 1459
id_compuestos_actividad    923, 2080, 2208, 5105, 8062, 8633, 11305, 1304...
Name: 978, dtype: object
cell_id                                                                 1460
id_compuestos_actividad    717, 923, 2080, 5268, 8062, 13048, 13590, 1444...
Name: 979, dtype: object
cell_id                                                                 1461
id_compuestos_actividad    717, 923, 2080, 5268, 8062, 13048, 13590, 1478...
Name: 980, dtype: object
cell_id                                                                 1462
id_compuestos_actividad    717, 923, 2080, 2208, 5105, 5268, 8062, 8633, ...
Name: 981, dtype: object
cell_id                                                                 1463
id_compuestos_actividad    717, 923, 2080, 5268, 8062, 13048, 13590, 1478...
Name: 982, dtype: object
cell_id                                                                 1464
id_compuestos_actividad    717, 923, 5268, 8062, 13048, 13590, 56713, 686...
Name: 983, dtype: object
cell_id                                                                 1465
id_compuestos_actividad    717, 923, 2080, 5268, 8062, 13048, 13590, 1478...
Name: 984, dtype: object
cell_id                                                                 1466
id_compuestos_actividad    717, 923, 2080, 2208, 5105, 5268, 8062, 8633, ...
Name: 985, dtype: object
cell_id                                                                 1467
id_compuestos_actividad    717, 923, 2080, 2208, 5105, 5268, 8062, 8633, ...
Name: 986, dtype: object
cell_id                                                                 1468
id_compuestos_actividad    717, 923, 2080, 5268, 8062, 11305, 13048, 1359...
Name: 987, dtype: object
cell_id                                                                 1469
id_compuestos_actividad    717, 923, 2080, 5268, 8062, 13048, 13590, 1478...
Name: 988, dtype: object
cell_id                                                                 1470
id_compuestos_actividad    717, 923, 5268, 8062, 13048, 13590, 14785, 148...
Name: 989, dtype: object
cell_id                                                                 1471
id_compuestos_actividad    717, 923, 2080, 2208, 5105, 5268, 8062, 8633, ...
Name: 990, dtype: object
cell_id                                                                 1472
id_compuestos_actividad    717, 923, 2080, 2208, 5105, 5268, 8062, 8633, ...
Name: 991, dtype: object
cell_id                                                                 1473
id_compuestos_actividad    717, 923, 2080, 2208, 5105, 5268, 8062, 8633, ...
Name: 992, dtype: object
cell_id                                                                 1474
id_compuestos_actividad    717, 5268, 13590, 56713, 68607, 75901, 78759, ...
Name: 993, dtype: object
cell_id                                                                 1475
id_compuestos_actividad    717, 923, 2080, 2208, 5105, 5268, 8062, 8633, ...
Name: 994, dtype: object
cell_id                                                                 1476
id_compuestos_actividad    717, 923, 2080, 2208, 5105, 5268, 8062, 8633, ...
Name: 995, dtype: object
cell_id                                                                 1477
id_compuestos_actividad    717, 923, 2080, 2208, 5105, 5268, 8062, 8633, ...
Name: 996, dtype: object
cell_id                                                                 1478
id_compuestos_actividad    717, 923, 2080, 2208, 5105, 5268, 8062, 8633, ...
Name: 997, dtype: object
cell_id                                                                 1479
id_compuestos_actividad    717, 923, 2080, 2208, 5105, 5268, 8062, 8633, ...
Name: 998, dtype: object
cell_id                                                                 1480
id_compuestos_actividad    717, 923, 2080, 5268, 8062, 13048, 13590, 5671...
Name: 999, dtype: object
cell_id                                                                 1481
id_compuestos_actividad    717, 923, 2080, 2208, 5105, 5268, 8062, 8633, ...
Name: 1000, dtype: object
cell_id                                                                 1482
id_compuestos_actividad    717, 923, 2080, 5268, 8062, 11305, 13048, 1359...
Name: 1001, dtype: object
cell_id                                                                 1483
id_compuestos_actividad    717, 923, 2080, 2208, 5105, 5268, 8062, 8633, ...
Name: 1002, dtype: object
cell_id                                                                 1484
id_compuestos_actividad    717, 923, 2080, 2208, 5105, 5268, 8062, 8633, ...
Name: 1003, dtype: object
cell_id                                                                 1486
id_compuestos_actividad    717, 923, 2080, 2208, 5105, 5268, 8062, 8633, ...
Name: 1004, dtype: object
cell_id                                                                 1487
id_compuestos_actividad    717, 2080, 2208, 5105, 5268, 8633, 11305, 1359...
Name: 1005, dtype: object
cell_id                                                                 1488
id_compuestos_actividad    717, 923, 2080, 2208, 5105, 5268, 8062, 8633, ...
Name: 1006, dtype: object
cell_id                                                                 1489
id_compuestos_actividad    923, 2080, 2208, 5105, 8062, 8633, 11305, 1304...
Name: 1007, dtype: object
cell_id                                                                 1490
id_compuestos_actividad    923, 2080, 2208, 5105, 8062, 8633, 11305, 1304...
Name: 1008, dtype: object
cell_id                                                                 1491
id_compuestos_actividad    717, 923, 2080, 2208, 5105, 5268, 8062, 8633, ...
Name: 1009, dtype: object
cell_id                                                                 1492
id_compuestos_actividad    717, 923, 2080, 2208, 5105, 5268, 8062, 8633, ...
Name: 1010, dtype: object
cell_id                                                                 1493
id_compuestos_actividad    717, 923, 2080, 2208, 5105, 5268, 8062, 8633, ...
Name: 1011, dtype: object
cell_id                                                                 1494
id_compuestos_actividad    717, 923, 2080, 5268, 8062, 13048, 13590, 1478...
Name: 1012, dtype: object
cell_id                                                                 1495
id_compuestos_actividad    717, 923, 2080, 2208, 5105, 5268, 8062, 8633, ...
Name: 1013, dtype: object
cell_id                                                                 1496
id_compuestos_actividad    717, 923, 2080, 2208, 5105, 5268, 8062, 8633, ...
Name: 1014, dtype: object
cell_id                                                                 1497
id_compuestos_actividad    717, 923, 2080, 2208, 5105, 5268, 8062, 8633, ...
Name: 1015, dtype: object
cell_id                                                                 1498
id_compuestos_actividad    717, 923, 2080, 2208, 5105, 5268, 8062, 8633, ...
Name: 1016, dtype: object
cell_id                                                                 1499
id_compuestos_actividad    717, 923, 2080, 2208, 5105, 5268, 8062, 8633, ...
Name: 1017, dtype: object
cell_id                                                                 1500
id_compuestos_actividad    717, 923, 2080, 2208, 5105, 5268, 8062, 8633, ...
Name: 1018, dtype: object
cell_id                                                                 1501
id_compuestos_actividad    717, 923, 2080, 2208, 5105, 5268, 8062, 8633, ...
Name: 1019, dtype: object
cell_id                                                                 1502
id_compuestos_actividad    717, 923, 2080, 2208, 5105, 5268, 8062, 8633, ...
Name: 1020, dtype: object
cell_id                                                                 1503
id_compuestos_actividad    717, 923, 2080, 2208, 5105, 5268, 8062, 8633, ...
Name: 1021, dtype: object
cell_id                                                                 1504
id_compuestos_actividad    717, 923, 2080, 5268, 8062, 13048, 13590, 1478...
Name: 1022, dtype: object
cell_id                                                                 1505
id_compuestos_actividad    717, 923, 2080, 5268, 8062, 13048, 13590, 1478...
Name: 1023, dtype: object
cell_id                                                                 1506
id_compuestos_actividad    717, 2208, 5105, 5268, 8633, 11305, 13590, 288...
Name: 1024, dtype: object
cell_id                                                                 1507
id_compuestos_actividad    717, 923, 2080, 2208, 5105, 5268, 8062, 8633, ...
Name: 1025, dtype: object
cell_id                                                                 1508
id_compuestos_actividad    717, 923, 2080, 5268, 8062, 13048, 13590, 1478...
Name: 1026, dtype: object
cell_id                                                                 1509
id_compuestos_actividad    717, 923, 2080, 2208, 5105, 5268, 8062, 8633, ...
Name: 1027, dtype: object
cell_id                                                                 1510
id_compuestos_actividad    717, 923, 2080, 2208, 5105, 5268, 8062, 8633, ...
Name: 1028, dtype: object
cell_id                                                                 1511
id_compuestos_actividad    605, 717, 923, 2080, 5268, 5985, 6243, 8062, 8...
Name: 1029, dtype: object
cell_id                                                                 1512
id_compuestos_actividad    717, 923, 2080, 2208, 5105, 5268, 8062, 8633, ...
Name: 1030, dtype: object
cell_id                                                                 1513
id_compuestos_actividad    2208, 5105, 8633, 11305, 51182, 62111, 71516, ...
Name: 1031, dtype: object
cell_id                                                                 1514
id_compuestos_actividad    2080, 5268, 14785, 14805, 36237, 68607, 99755,...
Name: 1032, dtype: object

Name: 1396, dtype: object
cell_id                    5744
id_compuestos_actividad    1219
Name: 1397, dtype: object
cell_id                                                                 5745
id_compuestos_actividad    8062, 11305, 187372, 232036, 368538, 1443351, ...
Name: 1398, dtype: object
cell_id                                                 5746
id_compuestos_actividad    691942, 1966980, 2262940, 2264903
Name: 1399, dtype: object
cell_id                            5748
id_compuestos_actividad    51961, 78759
Name: 1400, dtype: object
cell_id                                                                 5752
id_compuestos_actividad    11305, 152995, 319858, 419596, 470511, 520664,...
Name: 1401, dtype: object
cell_id                                           5756
id_compuestos_actividad    3965, 8873, 365281, 2321036
Name: 1402, dtype: object
cell_id                     5757
id_compuestos_actividad    78759
Name: 1403, dtype: object
cell_id                              5761
id_compuestos_actividad    187372, 365281
Name: 1404, dtype: object
cell_id                                  5767
id_compuestos_actividad    8873, 11305, 37812
Name: 1405, dtype: object
cell_id                                             5768
id_compuestos_actividad    63252, 125294, 460092, 460092
Name: 1406, dtype: object
cell_id                      5779
id_compuestos_actividad    462435
Name: 1407, dtype: object
cell_id                                                           5782
id_compuestos_actividad    8062, 11305, 172779, 368538, 387585, 462435
Name: 1408, dtype: object
cell_id                                                  5784
id_compuestos_actividad    1214046, 1214046, 1763587, 2146132
Name: 1409, dtype: object
cell_id                                                                 5787
id_compuestos_actividad    13048, 13048, 88797, 608601, 1277553, 1951876,...
Name: 1410, dtype: object
cell_id                                                           5788
id_compuestos_actividad    1214046, 2146132, 2154069, 2187100, 2187100
Name: 1411, dtype: object
cell_id                                               5791
id_compuestos_actividad    88797, 716337, 2346433, 2390700
Name: 1412, dtype: object
cell_id                           5792
id_compuestos_actividad    6968, 78759
Name: 1413, dtype: object
cell_id                                                           5796
id_compuestos_actividad    1214046, 1376110, 2321712, 2410657, 2458399
Name: 1414, dtype: object
cell_id                                                       5797
id_compuestos_actividad    13048, 88797, 1277553, 2355442, 2385179
Name: 1415, dtype: object
cell_id                           5803
id_compuestos_actividad    5970, 14805
Name: 1416, dtype: object
cell_id                                                                 5804
id_compuestos_actividad    9097, 9097, 68607, 373381, 1214046, 1926760, 2...
Name: 1417, dtype: object
cell_id                                                                 5806
id_compuestos_actividad    5295, 8062, 15738, 172779, 368538, 387585, 462...
Name: 1418, dtype: object
cell_id                    5807
id_compuestos_actividad    8062
Name: 1419, dtype: object
cell_id                       5808
id_compuestos_actividad    1377987
Name: 1420, dtype: object
cell_id                                                 5809
id_compuestos_actividad    1219, 8062, 14440, 28853, 2408852
Name: 1421, dtype: object
cell_id                       5815
id_compuestos_actividad    1957500
Name: 1422, dtype: object
cell_id                                                 5817
id_compuestos_actividad    426660, 2407071, 2407071, 2429934
Name: 1423, dtype: object
cell_id                                                              5819
id_compuestos_actividad    11305, 36237, 187372, 499179, 2363895, 2446633
Name: 1424, dtype: object
cell_id                                5821
id_compuestos_actividad    2361789, 2361789
Name: 1425, dtype: object
cell_id                             5827
id_compuestos_actividad    8062, 1277553
Name: 1426, dtype: object
cell_id                       5829
id_compuestos_actividad    2335270
Name: 1427, dtype: object
cell_id                      5833
id_compuestos_actividad    447415
Name: 1428, dtype: object
cell_id                              5834
id_compuestos_actividad    11305, 2454156
Name: 1429, dtype: object
cell_id                                             5836
id_compuestos_actividad    1763, 172779, 201200, 2382296
Name: 1430, dtype: object
cell_id                       5839
id_compuestos_actividad    1214046
Name: 1431, dtype: object
cell_id                      5845
id_compuestos_actividad    361469
Name: 1432, dtype: object
cell_id                       5847
id_compuestos_actividad    2410657
Name: 1433, dtype: object
cell_id                       5849
id_compuestos_actividad    2380147
Name: 1434, dtype: object
cell_id                                5850
id_compuestos_actividad    2356829, 2370244
Name: 1435, dtype: object
cell_id                       5854
id_compuestos_actividad    1951263
Name: 1436, dtype: object
cell_id                                             5855
id_compuestos_actividad    14785, 88232, 650126, 1817518
Name: 1437, dtype: object
cell_id                      5857
id_compuestos_actividad    336913
Name: 1438, dtype: object
cell_id                                                       5858
id_compuestos_actividad    13048, 88797, 1277553, 2355442, 2385179
Name: 1439, dtype: object
cell_id                                                                5859
id_compuestos_actividad    13048, 88797, 1277553, 2353370, 2355442, 2385179
Name: 1440, dtype: object
cell_id                     5860
id_compuestos_actividad    91783
Name: 1441, dtype: object
cell_id                                        5861
id_compuestos_actividad    373381, 2356829, 2370244
Name: 1442, dtype: object
cell_id                     5862
id_compuestos_actividad    11305
Name: 1443, dtype: object
cell_id                            5864
id_compuestos_actividad    22942, 78759
Name: 1444, dtype: object
cell_id                            5865
id_compuestos_actividad    1219, 142808
Name: 1445, dtype: object
cell_id                                      5867
id_compuestos_actividad    311051, 311122, 572645
Name: 1446, dtype: object
cell_id                       5868
id_compuestos_actividad    2375218
Name: 1447, dtype: object
cell_id                       5872
id_compuestos_actividad    1293234
Name: 1448, dtype: object
cell_id                       5881
id_compuestos_actividad    2301204
Name: 1449, dtype: object
cell_id                       5885
id_compuestos_actividad    2484361
Name: 1450, dtype: object
cell_id                                5887
id_compuestos_actividad    1376110, 2410657
Name: 1451, dtype: object
cell_id                                5888
id_compuestos_actividad    2410657, 2410657
Name: 1452, dtype: object
cell_id                                5889
id_compuestos_actividad    2354640, 2482982
Name: 1453, dtype: object
cell_id                       5890
id_compuestos_actividad    2366607
Name: 1454, dtype: object
cell_id                                5895
id_compuestos_actividad    1794474, 2301204
Name: 1455, dtype: object
cell_id                       5899
id_compuestos_actividad    2482982
Name: 1456, dtype: object
cell_id                                                                 5907
id_compuestos_actividad    14440, 1427050, 2399675, 2417350, 2421410, 246...
Name: 1457, dtype: object
cell_id                      5908
id_compuestos_actividad    579824
Name: 1458, dtype: object
cell_id                     5910
id_compuestos_actividad    78759
Name: 1459, dtype: object
cell_id                               5918
id_compuestos_actividad    232036, 2469807
Name: 1460, dtype: object
cell_id                           5921
id_compuestos_actividad    1219, 78759
Name: 1461, dtype: object
cell_id                                                  5922
id_compuestos_actividad    2341613, 2341613, 2484315, 2484315
Name: 1462, dtype: object
cell_id                                                           5923
id_compuestos_actividad    2083456, 2083457, 2083888, 2083889, 2083890
Name: 1463, dtype: object
cell_id                                                5924
id_compuestos_actividad    232036, 232036, 2469807, 2469807
Name: 1464, dtype: object
cell_id                      5927
id_compuestos_actividad    462435
Name: 1465, dtype: object
cell_id                             5928
id_compuestos_actividad    25906, 183934
Name: 1466, dtype: object
cell_id                      5930
id_compuestos_actividad    368538
Name: 1467, dtype: object
cell_id                                                                 5931
id_compuestos_actividad    923, 2471419, 2471677, 2471958, 2473036, 24753...
Name: 1468, dtype: object

In [49]:
#789 in perfil_afinidad['id_compuestos_actividad']
top3[top3['id_29']==5268]

Empty DataFrame
Columns: [comp_id, top3, id_29, pref_name, smiles]
Index: []